-- CreateTable
CREATE TABLE `pickup` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `services_id_1` VARCHAR(191) NULL,
    `i_product_type_id_2` VARCHAR(191) NULL,
    `i_priority_id_3` VARCHAR(191) NULL,
    `product_info_4` VARCHAR(191) NULL,
    `overwriting_cost_5` VARCHAR(191) NULL,
    `total_cost_6` VARCHAR(191) NULL,
    `collection_amount_7` VARCHAR(191) NULL,
    `i_payment_type_8` VARCHAR(191) NULL,
    `sender_category_1` VARCHAR(191) NULL,
    `pickup_type_2` VARCHAR(191) NULL,
    `pickup_date_3` VARCHAR(191) NULL,
    `sender_ref_no_4` VARCHAR(191) NULL,
    `sender_phone_5` VARCHAR(191) NULL,
    `sender_name_6` VARCHAR(191) NULL,
    `sender_client_id_7` VARCHAR(191) NULL,
    `sender_client_branch_id_8` VARCHAR(191) NULL,
    `sender_address_9` VARCHAR(191) NULL,
    `sender_country_id_10` VARCHAR(191) NULL,
    `sender_division_id_11` VARCHAR(191) NULL,
    `sender_district_id_12` VARCHAR(191) NULL,
    `sender_upazila_id_13` VARCHAR(191) NULL,
    `recipient_category_14` VARCHAR(191) NULL,
    `delivery_type_15` VARCHAR(191) NULL,
    `i_packaging_type_16` VARCHAR(191) NULL,
    `i_shipment_method_17` VARCHAR(191) NULL,
    `i_delivery_status_18` VARCHAR(191) NULL,
    `i_tracking_status_19` VARCHAR(191) NULL,
    `recipient_phone_20` VARCHAR(191) NULL,
    `recipient_name_21` VARCHAR(191) NULL,
    `recipient_client_id_22` VARCHAR(191) NULL,
    `recipient_client_branch_id_23` VARCHAR(191) NULL,
    `recipient_address_24` VARCHAR(191) NULL,
    `recipient_country_id_25` VARCHAR(191) NULL,
    `recipient_division_id_26` VARCHAR(191) NULL,
    `recipient_district_id_27` VARCHAR(191) NULL,
    `recipient_upazila_id_28` VARCHAR(191) NULL,
    `recipient_branch_id_29` VARCHAR(191) NULL,
    `i_sms_template_id_30` VARCHAR(191) NULL,
    `branch_id` INTEGER NULL,
    `current_branch` INTEGER NULL,
    `created` VARCHAR(40) NULL,
    `modified` VARCHAR(40) NULL,
    `creator` INTEGER NULL,
    `modifier` INTEGER NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
