-- AlterTable
ALTER TABLE `shipment` ADD COLUMN `dimension` VARCHAR(191) NULL,
    ADD COLUMN `gateway` VARCHAR(191) NULL,
    ADD COLUMN `i_relation_id` INTEGER NULL,
    ADD COLUMN `i_vendor_id` INTEGER NULL,
    ADD COLUMN `others_charge` VARCHAR(191) NULL,
    ADD COLUMN `price` VARCHAR(191) NULL,
    ADD COLUMN `priority` VARCHAR(191) NULL,
    ADD COLUMN `qty` VARCHAR(191) NULL,
    ADD COLUMN `rate` VARCHAR(191) NULL,
    ADD COLUMN `re_address` VARCHAR(191) NULL,
    ADD COLUMN `re_cell_no` VARCHAR(191) NULL,
    ADD COLUMN `re_city` VARCHAR(191) NULL,
    ADD COLUMN `re_company` VARCHAR(191) NULL,
    ADD COLUMN `re_country` VARCHAR(191) NULL,
    ADD COLUMN `re_customer_no` VARCHAR(191) NULL,
    ADD COLUMN `re_name` VARCHAR(191) NULL,
    ADD COLUMN `re_post_code` VARCHAR(191) NULL,
    ADD COLUMN `remarkes` VARCHAR(191) NULL,
    ADD COLUMN `service_charge` VARCHAR(191) NULL,
    ADD COLUMN `sms_send` VARCHAR(191) NULL,
    ADD COLUMN `track_status` VARCHAR(191) NULL,
    ADD COLUMN `tracking` LONGTEXT NULL,
    ADD COLUMN `weight` VARCHAR(191) NULL;
